#!/usr/bin/env bash
# Run the static-helper gate under whichever authority this shell has, or say
# plainly that it did not run.
#
# TWO AUTHORITIES, ONE GATE. The checks are the same everywhere -- every
# library in libs/static_helpers.txt compiles with --mm:arc --app:staticlib,
# and none defines or uses a Nim `ref` -- and so is the refusal to run them
# with a compiler or a source tree the gate cannot vouch for. What differs is
# how it vouches:
#
#   * the Nix dev shell: `runquota-static-helper-gate`, generated by flake.nix
#     (`staticHelperGate`), which accepts only a pinned /nix/store Nim and an
#     immutable /nix/store snapshot of the source
#     (scripts/check_static_helpers.sh). Preferred wherever it exists.
#   * the reprobuild dev shell on Windows (`repro exec -- just test`), whose
#     toolchain is realised from pinned release archives into reprobuild's
#     tool store: scripts/static_helper_gate_toolstore.sh, which verifies that
#     toolchain against scripts/static_helper_gate_toolstore.pins and the
#     source against git, by content.
#
# Anywhere else this FAILS, naming what went unchecked. Absence is never a
# skip: a run that did not check the static helpers must not read as one that
# did.
set -euo pipefail

if command -v runquota-static-helper-gate >/dev/null 2>&1; then
  exec runquota-static-helper-gate "$@"
fi

case "${OSTYPE:-}" in
msys* | cygwin*)
  exec "${BASH}" "$(dirname "${BASH_SOURCE[0]}")/static_helper_gate_toolstore.sh" "$@"
  ;;
esac

cat >&2 <<'MSG'
runquota static helper gate: NOT RUN.
  `runquota-static-helper-gate` is provided by the Nix dev shell (flake.nix
  `staticHelperGate`), whose authority checks require a pinned /nix/store Nim
  and an immutable /nix/store source snapshot; the tool-store authority
  (scripts/static_helper_gate_toolstore.sh) exists for the reprobuild dev
  shell on Windows. This shell has neither.
  Unchecked by this run: that every library in libs/static_helpers.txt
  compiles with --mm:arc --app:staticlib, and that none defines or uses a
  Nim `ref` type.
  Run `just test` inside `nix develop` (or `repro exec -- just test`, which
  on Linux and macOS is the flake's dev shell) to check them.
MSG
exit 1
