#!/usr/bin/env bash
# Run the static-helper gate, or say plainly that it did not run.
#
# `runquota-static-helper-gate` is generated by flake.nix (`staticHelperGate`)
# and exists only inside the Nix dev shell. That is deliberate: its authority
# checks accept only a pinned /nix/store Nim and an immutable /nix/store
# snapshot of the source (scripts/check_static_helpers.sh), so there is no
# honest way to run it anywhere else.
#
# What this wrapper replaces is the bare call the Justfile used to make, which
# outside the dev shell died with bash's "command not found" and exit 127 --
# a failure that named neither the gate nor what had gone unchecked. Absence
# is still a FAILURE here, never a skip: a run that did not check the static
# helpers must not read as one that did.
set -euo pipefail

if command -v runquota-static-helper-gate >/dev/null 2>&1; then
  exec runquota-static-helper-gate "$@"
fi

cat >&2 <<'MSG'
runquota static helper gate: NOT RUN.
  `runquota-static-helper-gate` is provided only by the Nix dev shell
  (flake.nix `staticHelperGate`): its authority checks require a pinned
  /nix/store Nim and an immutable /nix/store source snapshot.
  Unchecked by this run: that every library in libs/static_helpers.txt
  compiles with --mm:arc --app:staticlib, and that none defines or uses a
  Nim `ref` type.
  Run `just test` inside `nix develop` to check them.
MSG
exit 1
