name: Release

on:
  workflow_dispatch:
  push:
    branches: [release/unified-0.1.0]
    tags: ['v*']

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: metacraft-labs/metacraft-github-actions/.github/workflows/release-tools.yml@4984a2dd55d5c403e6048dc0308a984156bcb6c8
    with:
      tooling-ref: 4984a2dd55d5c403e6048dc0308a984156bcb6c8
    secrets: inherit
